8.x 2.x  2757701  enforce unique attribute in product variations
drupalcommerce/commerce pull request #429
Opened 2016-06-29 10:16 UTC by ndf

Initial setup with a failing test and boilerplate for the attribute Constraint class

2016-11-22 08:20 UTC, steveoliver requested changes
Would be great to have this in.  Let's the get [coding standards issues](https://travis-ci.org/drupalcommerce/commerce/jobs/142247069#L970) fixed + consider my comments for changes.

2016-11-22 08:20 UTC, steveoliver commented on modules/product/src/Plugin/Validation/Constraint/ProductVariationAttributeConstraintValidator.php
> +   * Constructs a new ProductVariationTypeForm object.
wrong class name

2016-11-22 08:20 UTC, steveoliver commented on modules/product/src/Plugin/Validation/Constraint/ProductVariationAttributeConstraint.php
> +class ProductVariationAttributeConstraint extends CompositeConstraintBase {
maybe call it ProductVariationUniqueAttributeConstraint for clarity?

2016-11-26 03:29 UTC, mglaman commented
@steveoliver this is pretty stale (pre-beta, even) from Drupal Dev Days. Maintainers can push to it, but it might be best to export current work to a patch on Drupal.org, then carry it on in a new PR (since only maintainers can push.)

2020-02-07 14:41 UTC, bojanz commented
Closing, since the PR is severely outdated

2020-02-07 14:41 UTC, closed without merging