Issue #2798301 - Define admin label to checkout panes
drupalcommerce/commerce pull request #505
Opened 2016-09-23 07:05 UTC by mitrpaka

2016-09-23 15:47 UTC, mglaman commented on modules/checkout/src/Plugin/Commerce/CheckoutPane/CheckoutPaneBase.php
> +    $admin_label = $this->pluginDefinition['admin_label'];
Have the plugin manager set this. That if the `admin_label` is empty, prepopulate it to the value of `label`. That way all processing is done on discovery and cached.

2016-09-23 15:47 UTC, mglaman requested changes

2016-09-24 08:42 UTC, mitrpaka commented on modules/checkout/src/Plugin/Commerce/CheckoutPane/CheckoutPaneBase.php
> +    $admin_label = $this->pluginDefinition['admin_label'];
Thanks for the review and guidance way forward. PR updated.

2016-09-27 21:41 UTC, bojanz commented
Tweaked and committed in 60bae651b76ff256b470702393354eb7517177b6.

2016-09-27 21:41 UTC, closed without merging