Issue #2803257: OrderRefresh must not touch already completed orders
drupalcommerce/commerce pull request #509
Opened 2016-09-23 21:26 UTC by mglaman

2016-09-23 21:51 UTC, bojanz commented on modules/order/src/OrderRefresh.php
> +
Extra newline? :P

2016-09-23 21:51 UTC, bojanz commented on modules/order/tests/src/Kernel/OrderRefreshTest.php
> +
And another one!

2016-09-23 21:51 UTC, bojanz requested changes

2016-09-23 21:52 UTC, mglaman commented on modules/order/src/OrderRefresh.php
> +
I'll get you.

2016-09-24 00:25 UTC, bojanz commented
Committed in f2bf286979dda5986fc0b47ee77c96fe5dc480f3.

2016-09-24 00:25 UTC, closed without merging