Issue - #2809967: Modules and their associated plugins should provide plugin.yml
drupalcommerce/commerce pull request #521
Opened 2016-10-02 02:08 UTC by scotthooker

Add plugin_type.yml to commerce_checkout similar to how address does.

2016-10-02 08:40 UTC, mglaman requested changes

2016-10-02 08:40 UTC, mglaman commented on modules/checkout/commerce_checkout.plugin_type.yml
> +  plugin_definition_decorator_class: Drupal\commerce_checkout\PluginDefinition\CheckoutPanePluginDefinitionDecorator
We don't have this class.

2016-10-02 08:40 UTC, mglaman commented on modules/checkout/commerce_checkout.plugin_type.yml
> +  plugin_definition_decorator_class: Drupal\commerce_checkout\PluginDefinition\CheckoutFlowPluginDefinitionDecorator
This also does not exist.

2016-10-02 09:10 UTC, scotthooker commented
As there is nothing special about our plugins we can just provide the default one from plugin. 
What other commerce sub modules contain plugins? 

1. Checkout
 - checkout flow
 - checkout pane
...

2016-10-02 09:12 UTC, scotthooker commented on modules/checkout/commerce_checkout.plugin_type.yml
> +  plugin_definition_decorator_class: Drupal\commerce_checkout\PluginDefinition\CheckoutFlowPluginDefinitionDecorator
As there is nothing special about our plugins we can just provide the default one from plugin. Updated.

2016-10-02 09:12 UTC, scotthooker commented on modules/checkout/commerce_checkout.plugin_type.yml
> +  plugin_definition_decorator_class: Drupal\commerce_checkout\PluginDefinition\CheckoutPanePluginDefinitionDecorator
As there is nothing special about our plugins we can just provide the default one from plugin. Updated

2016-10-02 09:19 UTC, mglaman commented
No idea. As far as I know this is just for the Plugin module, and not 100% sure what this really gains us. Just some developer experience around plugins? Or what does it provide as a direct gain.

2016-10-02 09:36 UTC, scotthooker commented
We supply one in address module - as far as the developer experience goes I use it like I do the old views_field list in d7. 

I included it in my own custom module prior to porting it to here once seeing we include it in address.

2016-10-02 15:30 UTC, scotthooker commented
@bojanz any specific reason that you added the definition to address module?

2016-10-02 17:53 UTC, bojanz commented
It's integration for the Plugin contrib, Bart wanted it, figured it doesn't hurt.

2016-10-02 17:54 UTC, scotthooker commented
I'll add the yaml for them too. I think its quite handy.

2016-10-02 18:58 UTC, scotthooker commented
Added definitions for payment and promotion

2016-11-30 17:42 UTC, bojanz commented
Def doesn't hurt. Added trailing newlines and some spaces, committed in 7c327cb0288e100e6d01de45f01c549604563c72.

2016-11-30 17:42 UTC, closed without merging