Issue #2848183 : Implement test for TimestampEventSubscriber.
drupalcommerce/commerce pull request #624
Opened 2017-02-01 11:07 UTC by vasike

2017-02-01 15:04 UTC, mglaman requested changes

2017-02-01 15:04 UTC, mglaman commented on modules/order/tests/src/Kernel/TimestampEventTest.php
> +    $this->assertEquals(\Drupal::service('commerce.time')->getRequestTime(), $order->getPlacedTime(), 'During placement transition, the order placed timestamp is set to the request time.');
In kernel test, let's use `$this->container->get('commerce.time')`

2017-02-01 15:04 UTC, mglaman commented on modules/order/src/EventSubscriber/TimestampEventSubscriber.php
> +      $order->setPlacedTime(\Drupal::service('commerce.time')->getRequestTime());
Let's inject this via DI

2017-02-01 16:06 UTC, vasike commented on modules/order/src/EventSubscriber/TimestampEventSubscriber.php
> +      $order->setPlacedTime(\Drupal::service('commerce.time')->getRequestTime());
done

2017-02-01 16:06 UTC, vasike commented on modules/order/tests/src/Kernel/TimestampEventTest.php
> +    $this->assertEquals(\Drupal::service('commerce.time')->getRequestTime(), $order->getPlacedTime(), 'During placement transition, the order placed timestamp is set to the request time.');
done. thanks

2017-12-08 21:01 UTC, mglaman approved these changes

2017-12-08 21:53 UTC, mglaman commented
Committed in 631ee7d

2017-12-08 21:53 UTC, closed without merging