Issue #2855836 by mglaman, vasike: Coupon codes need unique value validation constraint
drupalcommerce/commerce pull request #659
Opened 2017-03-02 12:58 UTC by vasike

2017-03-03 12:24 UTC, mglaman requested changes
Code looks good to me. It's pretty much `\Drupal\Core\Validation\Plugin\Validation\Constraint\UniqueFieldValueValidator` but with specific message.

2017-03-03 12:24 UTC, mglaman commented on modules/promotion/tests/src/Kernel/CouponValidationTest.php
> +    $this->assertEquals($violations[0]->getMessage(), 'A coupon with code %value already exists. Enter a unique code.');
Can we update the test to change the code value and run validations again? I'd like the test to prove we can still save the coupon with the validation now added. We have tests that should prove this, but I'd rather be explicit in our test coverage.

2017-03-03 14:09 UTC, vasike commented on modules/promotion/tests/src/Kernel/CouponValidationTest.php
> +    $this->assertEquals($violations[0]->getMessage(), 'A coupon with code %value already exists. Enter a unique code.');
done

2017-03-03 14:20 UTC, mglaman commented on modules/promotion/tests/src/Kernel/CouponValidationTest.php
> +    $this->assertEquals($violations[0]->getMessage(), 'A coupon with code %value already exists. Enter a unique code.');
💃 yay

2017-03-03 14:20 UTC, mglaman approved these changes

2017-03-03 15:28 UTC, mglaman commented
@bojanz this looks good to me, now. My main Q is just should we use custom validator or reuse core one. But seems better to be verbose.

2017-03-10 12:59 UTC, bojanz commented
Committed in 0a7d06cb05855d41f9af595d380841d25a21c695b.

2017-03-10 12:59 UTC, closed without merging

2017-03-10 13:00 UTC, bojanz commented
Committed in 0a7d06cb05855d41f9af595d380841d25a21c695b.