Issue #2828525: Implement manual payment gateways
drupalcommerce/commerce pull request #672
Opened 2017-03-15 13:17 UTC by vasike

2017-03-15 13:31 UTC, mglaman commented on modules/payment/src/Plugin/Commerce/PaymentGateway/Manual.php
> +        if ($convert < REQUEST_TIME) {
:) Darn `REQUEST_TIME` global

2017-03-15 13:32 UTC, mglaman commented on modules/payment/src/Plugin/Commerce/PaymentGateway/Manual.php
> +    $payment->setAuthorizedTime(REQUEST_TIME);
Deprecated global usage

2017-03-15 13:33 UTC, mglaman requested changes
Various `REQUEST_TIME` usages, and I do not see any tests

2017-03-15 14:37 UTC, vasike commented on modules/payment/src/Plugin/Commerce/PaymentGateway/Manual.php
> +    $payment->setAuthorizedTime(REQUEST_TIME);
i was aware. i'll replace them

2017-03-17 12:56 UTC, mglaman requested changes
Anything manually building a path for `drupalGet` should use `Url::fromRoute`.

Also, I'd like an "admin" test which verifies the creation of a manual payment method from the config area.

2017-03-17 12:56 UTC, mglaman commented on modules/payment/tests/src/Functional/ManualPaymentAdminTest.php
> +    $this->paymentUri = 'admin/commerce/orders/' . $this->order->id() . '/payments';
We should generate this via `Url::fromRoute` with proper parameters. I know `drupalGet` tries, but we should use proper generation.

2017-05-31 11:47 UTC, bojanz commented
Final version committed in 753eabf8db02e1d2a9e167056b5e34bf5a763aa1.

2017-05-31 11:47 UTC, closed without merging