Issue #2861181 : Better handling of customer remote IDs for payments.
drupalcommerce/commerce pull request #676
Opened 2017-03-16 13:06 UTC by vasike

2017-03-16 13:20 UTC, mglaman reviewed
Just some concerns around the post update function.

2017-03-16 13:20 UTC, mglaman commented on modules/payment/commerce_payment.post_update.php
> +  $result = \Drupal::entityQuery('user')->exists('commerce_remote_id')->execute();
Wouldn't we only want to run this the first time, and I think we could just do a count query

2017-03-16 13:20 UTC, mglaman commented on modules/payment/commerce_payment.post_update.php
> +  $result = array_slice($result, $sandbox['current'], $limit);
Why not put a range on the query instead

2017-03-16 13:32 UTC, vasike commented on modules/payment/commerce_payment.post_update.php
> +  $result = \Drupal::entityQuery('user')->exists('commerce_remote_id')->execute();
is it necessary?

2017-03-16 13:32 UTC, vasike commented on modules/payment/commerce_payment.post_update.php
> +  $result = array_slice($result, $sandbox['current'], $limit);
is it necessary?

2017-03-16 15:22 UTC, bojanz commented on modules/payment/commerce_payment.post_update.php
> +  $result = \Drupal::entityQuery('user')->exists('commerce_remote_id')->execute();
A count query would probably be more efficient, let's do that.

2017-03-16 16:03 UTC, vasike commented on modules/payment/commerce_payment.post_update.php
> +  $result = \Drupal::entityQuery('user')->exists('commerce_remote_id')->execute();
it should be done now

2017-03-17 10:14 UTC, bojanz requested changes

2017-03-17 10:14 UTC, bojanz commented on modules/payment/commerce_payment.post_update.php
> +  $result = \Drupal::entityQuery('user')->exists('commerce_remote_id')->execute();
We should run the count query only under if (!isset($sandbox['current'])) {
After that it's cached in $sandbox.

Then run the real query with a range each time.

2017-03-17 10:14 UTC, bojanz commented on modules/payment/commerce_payment.post_update.php
> +  uasort($payment_gateways, [$payment_gateway_storage->getEntityType()->getClass(), 'sort']);
You should be able to use $payment_gateway_storage->getEntityType()->getProvider() to get the module.

2017-03-17 10:14 UTC, bojanz commented on modules/payment/src/Entity/PaymentMethod.php
> +  public function getOwnerRemoteId() {
Is there a point in having these methods? We usually need the remote customer ID before creating a payment method, so we need them on PaymentGatewayBase instead.

2017-03-17 10:18 UTC, vasike commented on modules/payment/src/Entity/PaymentMethod.php
> +  public function getOwnerRemoteId() {
i also thought the same initially. but working on it looks like PaymentMethod entity methods

2017-03-17 11:45 UTC, vasike commented on modules/payment/commerce_payment.post_update.php
> +  $result = \Drupal::entityQuery('user')->exists('commerce_remote_id')->execute();
should be done

2017-03-17 11:46 UTC, vasike commented on modules/payment/commerce_payment.post_update.php
> +  uasort($payment_gateways, [$payment_gateway_storage->getEntityType()->getClass(), 'sort']);
no idea, what you mean

2017-07-12 16:59 UTC, bojanz commented
Committed in 14786dd4afa8e94e5246199759e10ff19ac0f348.

2017-07-12 16:59 UTC, closed without merging