Issue - 2862434
drupalcommerce/commerce pull request #683
Opened 2017-03-21 12:40 UTC by haringsrob

2017-03-21 13:08 UTC, mglaman requested changes
Minor nit picks, overall I like the change and love the proper test coverage :)

2017-03-21 13:08 UTC, mglaman commented on modules/order/src/Form/OrderReassignForm.php
> +    $assignment_service->assign($this->order, User::load($values['uid']), TRUE);
Not sure if the approach is just to get it up and tests run for quick and dirty, but we should inject the service + user storage

2017-03-21 13:08 UTC, mglaman commented on modules/order/tests/src/Functional/OrderAdminTest.php
> +    $this->assertSession()->statusCodeEquals(200);
No need to assert status code, as following items would fail if not 200.

2017-03-21 13:08 UTC, mglaman commented on modules/order/tests/src/Kernel/OrderAssignmentTest.php
> +    $assignment_service = \Drupal::service('commerce_order.order_assignment');
`$this->container->get()`

2017-03-21 13:08 UTC, mglaman commented on modules/order/tests/src/Kernel/OrderAssignmentTest.php
> +    $assignment_service = \Drupal::service('commerce_order.order_assignment');
`$this->container->get()`

2017-03-21 13:08 UTC, mglaman commented on modules/order/tests/src/Kernel/OrderAssignmentTest.php
> +    $assignment_service = \Drupal::service('commerce_order.order_assignment');
`$this->container->get()`

2017-03-21 13:08 UTC, mglaman commented on modules/order/tests/src/Kernel/OrderAssignmentTest.php
> +    $assignment_service = \Drupal::service('commerce_order.order_assignment');
`$this->container->get()`

2017-03-21 13:08 UTC, mglaman commented on tests/src/Functional/CommerceBrowserTestBase.php
> +    $storage = \Drupal::entityTypeManager()->getStorage($entity->getEntityTypeId());
`$this->container->get()`

2017-03-21 13:26 UTC, haringsrob commented
Thanks @mglaman! 

Everything should be updated.

2017-03-21 13:28 UTC, mglaman approved these changes

2017-03-21 13:34 UTC, mglaman commented
Bah. Looks like Coder updated in the process and caught things outside of this PR. Like array syntax and a period :P @haringsrob the PHP7 build has output if you want to fix phpcs errors

2017-03-21 14:03 UTC, haringsrob commented
Yea I noticed, resolved all of them now

2017-03-21 14:59 UTC, bojanz commented on modules/order/src/Form/OrderReassignForm.php
> +  protected $order_assignment_service;
1) You can't use snake_case in a class property
2) We never append _service to any object. You want $orderAssignment.

2017-03-21 15:00 UTC, bojanz commented on modules/order/src/Form/OrderReassignForm.php
> +
Don't introduce newlines where there weren't any.

2017-03-21 15:00 UTC, bojanz commented on modules/order/src/Form/OrderReassignForm.php
> +    $this->order_assignment_service->assign($this->order, User::load($values['uid']), TRUE);
Can't use User::load() in a class.

2017-03-21 15:37 UTC, haringsrob commented
@bojanz, I have made the changes, The assign method is now left untouched except the removal of the if statement at the start

2017-03-21 16:29 UTC, mglaman requested changes
Two more nits

2017-03-21 16:29 UTC, mglaman commented on modules/order/src/Form/OrderReassignForm.php
> +  protected $OrderAssignment;
$orderAssignment

2017-03-21 16:29 UTC, mglaman commented on modules/order/src/Form/OrderReassignForm.php
> +      $container->get('entity.manager')->getStorage('user')
It should be `entity_type.manager`, and usually we just inject that, then in constructor pluck out the storages we need.

2017-03-23 09:17 UTC, haringsrob commented
Makes sense! Fixed

2018-12-16 20:19 UTC, bojanz commented
Rerolled on the issue, let's wrap it up there: https://www.drupal.org/project/commerce/issues/2862434

2018-12-16 20:19 UTC, closed without merging