issue #2859834 implementation of links in checkout progress block
drupalcommerce/commerce pull request #686
Opened 2017-03-22 15:47 UTC by finnef

2017-03-22 17:45 UTC, finnef commented
DO: https://www.drupal.org/node/2859834

2017-03-22 18:12 UTC, bojanz commented
We also need a setting for enabling this, like the D7 module had.

2017-03-22 19:53 UTC, onatalushko commented on modules/checkout/src/Plugin/Block/CheckoutProgressBlock.php
> +        ])->toString();
maybe ->to Renderable() will be better here ?

2017-03-22 19:59 UTC, mglaman requested changes

2017-03-22 19:59 UTC, mglaman commented on modules/checkout/src/Plugin/Block/CheckoutProgressBlock.php
> +        ])->toString();
Should always be renderable, unless that does fail

2017-03-22 19:59 UTC, mglaman commented on modules/checkout/templates/commerce-checkout-progress.html.twig
> +      <li class="checkout-progress--step checkout-progress--step__{{ step.position }}">{{ step.label | raw }}</li>
If we remove `raw` toRenderable should be fine

2017-03-22 21:43 UTC, finnef commented
changed to Renderable() and removed | raw.
Also added config checkbox

2017-03-23 04:06 UTC, mglaman requested changes
```
    1)
    Drupal\Tests\commerce_checkout\Kernel\ChainCheckoutFlowResolverTest::testCheckoutFlowResolution
    Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for
    commerce_checkout.commerce_checkout_flow.default with the following errors:
    commerce_checkout.commerce_checkout_flow.default:configuration.display_checkout_progress_breadcrumb_links
    missing schema
```

the new option needs to be added to the module's schema.

can we also update a test where it clicks a link and goes back and continues?

2017-03-24 11:24 UTC, finnef commented
Added tests and schema.

2017-03-24 13:23 UTC, mglaman requested changes
Almost thumbs up here. However our tests do not prove this works or document the interaction.

2017-03-24 13:23 UTC, mglaman commented on modules/checkout/tests/src/Functional/CheckoutOrderTest.php
> +    $this->assertSession()->elementNotExists('css', '.block-commerce-checkout-progress li.checkout-progress--step > a');
So we assert it's not a link, however we do not prove the feature works in any test

2017-03-24 13:52 UTC, finnef commented on modules/checkout/tests/src/Functional/CheckoutOrderTest.php
> +    $this->assertSession()->elementNotExists('css', '.block-commerce-checkout-progress li.checkout-progress--step > a');
The test to use the link to move back and fwd through the checkout steps is in testGuestOrderCheckout. The test there is no link by default is in testRegisterOrderCheckout.

2017-03-24 20:38 UTC, mglaman approved these changes

2017-03-24 20:38 UTC, mglaman commented on modules/checkout/tests/src/Functional/CheckoutOrderTest.php
> +    $this->assertSession()->elementNotExists('css', '.block-commerce-checkout-progress li.checkout-progress--step > a');
Oh duh, wow i totally missed that. All good then!

2017-09-06 14:08 UTC, bojanz commented
Continued (rebased) in #732.

2017-09-06 14:08 UTC, closed without merging