issue #2859570 Create a generic entity bundle delete form
drupalcommerce/commerce pull request #688
Opened 2017-03-22 17:41 UTC by finnef

2017-03-22 17:46 UTC, finnef commented
DO: https://www.drupal.org/node/2859570

2017-03-22 19:56 UTC, mglaman requested changes

2017-03-22 19:56 UTC, mglaman commented on src/Form/CommerceBundleEntityDeleteFormBase.php
> +      ->condition('type', $this->entity->id())
You need to check the content entity type's definition to get the proper bundle key.

2017-03-22 19:57 UTC, mglaman commented on src/Form/CommerceBundleEntityDeleteFormBase.php
> +      ->condition('type', $this->entity->id())
Forgot to add: not sre if that's why the functional tests are breaking or not.

2017-03-23 04:09 UTC, mglaman commented
Shoot, I thought last change would fix tests. Not sure why, it might just be tweaks to expected error message.

2017-03-23 16:06 UTC, finnef commented
I tried this test locally and it succeeds. The Travis CI fails on 
Drupal\Tests\commerce_order\Functional\OrderTypeTest::testDeleteOrderType (line 92)
Why I don't know. Hard to get screenshots of the CI tester I would guess?

2017-03-23 16:35 UTC, finnef commented
Found the failure. Changed some test strings to match the form.

2017-03-23 19:08 UTC, finnef commented
On my latest patch all tests have passed. I don't know why travis says the checks failed...?

2017-03-23 20:22 UTC, mglaman commented
@finnef are you running phpunit locally or run-tests? I've had issues where local with phpunit is fine, but concurrent in run-tests goes nuts.

2017-03-23 20:29 UTC, finnef commented
I run phpunit... but my previous comment was about travis: if you check the current 'failed' details, all tests have passed. Strange.

2017-03-23 20:34 UTC, mglaman commented
oh, I didn't look. It's coding standards error. I'll just edit in UI for you

```
FILE: ...ommerce/commerce/src/Form/CommerceBundleEntityDeleteFormBase.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
----------------------------------------------------------------------
 34 | WARNING | [x] A comma should follow the last multiline array item.
    |         |     Found: ) (Drupal.Array.Array.CommaLastItem)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
Time: 670ms; Memory: 10Mb
```

2017-03-23 20:36 UTC, mglaman approved these changes

2017-03-24 20:10 UTC, mglaman commented
\o/ yay

2017-04-21 14:09 UTC, merged