#2770731 Adjustment label: how the promotion appears on the order total
drupalcommerce/commerce pull request #706
Opened 2017-04-03 20:22 UTC by smmccabe

2017-04-03 20:43 UTC, mglaman requested changes
There's no test coverage.

2017-06-01 03:03 UTC, mglaman approved these changes

2017-06-01 03:03 UTC, mglaman commented
There is. I just didn't see it.

2017-08-14 17:48 UTC, heddn commented
Fixed up this PR in #775.

2017-09-11 11:13 UTC, closed without merging