Issue #2867046 by vasike, bojanz: Create promotions test for cart.
drupalcommerce/commerce pull request #710
Opened 2017-04-05 15:14 UTC by vasike

2017-04-05 16:44 UTC, mglaman requested changes
This doesn't feel like a proper fix and allows for bugs to still happen outside of this scope.

2017-04-05 16:44 UTC, mglaman commented on modules/promotion/src/Plugin/Commerce/PromotionOffer/OrderPercentageOff.php
> +    if ($order->getTotalPrice()) {
This sounds like a bug where the order should _always_ return a total price. I say we remove this line, prove test fails and fix order entity for a proper TDD approach.

2017-04-05 16:57 UTC, vasike commented on modules/promotion/src/Plugin/Commerce/PromotionOffer/OrderPercentageOff.php
> +    if ($order->getTotalPrice()) {
updated with other approach, you suggested

2017-04-05 18:06 UTC, mglaman approved these changes

2017-04-05 18:06 UTC, mglaman commented
@vasike wonderful :) Thank you for update. It's a much more hardened approach that will prevent others in contrib / custom implementation from hitting error.

2017-04-21 19:25 UTC, bojanz commented
Committed an improved version in 005e9046af683bed84087d8c9f7fa0d196432657.

2017-04-21 19:25 UTC, closed without merging