Issue #2794909 by drugan, mglaman, Frank HH-germany, agoradesign, iam…
drupalcommerce/commerce pull request #755
Opened 2017-07-03 15:48 UTC by mglaman

…puma: Make the quantity field configurable to include HTML properties such as 'Step' property

2017-07-03 15:54 UTC, mglaman commented on modules/cart/src/Plugin/views/field/EditQuantity.php
> +      $form_display = commerce_get_entity_display('commerce_order_item', $order_item->bundle(), 'form');
@bojanz in general, I believe we need to have the cart form mimic the order item form display as much as possible. This kind of hackishly does that. Would rather save for a follow up to limit scope.

2017-07-03 15:54 UTC, mglaman commented on modules/order/src/Entity/OrderItem.php
> +      ->setSetting('min', 0)
Setting this prevents negative quantity. Kind of out of scope, but part of bigger problem.

2017-07-03 15:54 UTC, mglaman commented on modules/product/config/optional/core.entity_form_display.commerce_order_item.default.default.yml
> +    type: commerce_number
Setting default will cause cart form to respect step.

2017-07-06 11:59 UTC, finnef commented
Code reviewed and OK. Lots of things you could add, but let's keep the scope as small as possible and get this committed.
Test on my Commerce installation worked fine. Like the improvement in UI.

2017-07-06 13:43 UTC, bojanz requested changes

2017-07-06 13:43 UTC, bojanz commented on modules/order/src/Entity/OrderItem.php
>          'type' => 'number',
The display options were not updated to use commerce_number instead of number.

2017-07-06 13:43 UTC, bojanz commented on src/Plugin/Field/FieldWidget/CommerceNumberWidget.php
> +class CommerceNumberWidget extends NumberWidget {
We never prefix classes with Commerce.

2017-07-06 13:43 UTC, bojanz commented on src/Plugin/Field/FieldWidget/CommerceNumberWidget.php
> +      'placeholder' => '',
Placeholder is already defined by the parent method.

2017-07-06 13:43 UTC, bojanz commented on src/Plugin/Field/FieldWidget/CommerceNumberWidget.php
> + *     "integer",
Doesn't make sense to allow this widget on integer fields.

2017-07-06 13:43 UTC, bojanz commented on src/Plugin/Field/FieldWidget/CommerceNumberWidget.php
> + *   label = @Translation("Commerce number field"),
Label is a bit ugly. Perhaps we name it "Decimal number field" and prefix the class name accordingly?

2017-07-06 13:43 UTC, bojanz commented on src/Plugin/Field/FieldWidget/CommerceNumberWidget.php
> +    $element['step'] = [
We should add a comment explaining why we're not using the commerce_number field (can't use both the HTML5 input element and have locale-specific inputs with commas like commerce_number allows)

2017-07-06 13:58 UTC, bojanz commented on src/Plugin/Field/FieldWidget/CommerceNumberWidget.php
> +      '#min' => 0,
We can take #min and #max from field settings, like the parent does.

2017-07-06 22:33 UTC, bojanz commented
Commited in 8becee97bdb7f1f0ec86215b789dea9f4b0ae8e1.

2017-07-06 22:33 UTC, closed without merging