Expand the commerce_profile_select form element with the ability to reuse profiles
drupalcommerce/commerce pull request #760
Opened 2017-07-12 22:31 UTC by bojanz

Continuation of #631, done by czigor and mglaman.

2017-07-23 19:43 UTC, bojanz commented on modules/order/src/Element/ProfileSelect.php
> +class ProfileSelect extends FormElement {
This is reverting the fix from #2857051.

Guessing by accident, since this PR is older than that fix.

2017-08-24 10:31 UTC, ymhuang0808 requested changes
Support multiple form elements in the same form for commerce_shipping module

2017-08-24 10:31 UTC, ymhuang0808 commented on modules/order/src/Element/ProfileSelect.php
> +        '#name' => 'edit_profile',
I'm testing the patch when enabling commerce_shipping module. 

Because, the commerce_shipping also uses the `ProfileSelect` element, in checkout page, there are multiple submit buttons with same `#name`. If the `edit_button` element is clicked, the trigger element will be wrong. 

In my testing, when I clicked the "Edit" button, the trigger element was the "Continue to review" button. However, the expected and correct trigger element should be "Edit" button. The problem may result from the same value of `#name` and more detail is in issue [#2546700](https://www.drupal.org/node/2546700). 

In order to prevent the situation, we should have a workaround for the issue to make the value of `#name` unique. 
My rough implementation:

```
$form_name = (isset($element['#parents'])) ? implode('_', $element['#parents']) . '_' : '';
$form_name .= 'edit_profile';
```

And the value of the `#name` is `$form_name`.

2017-08-24 10:31 UTC, ymhuang0808 commented on modules/order/src/Element/ProfileSelect.php
> +      '#element_mode' => $form_state->get('element_mode') ?: 'view',
If the multiple `ProfileSelect` form elements exist in the same form (eg. in checkout page, the shipping info and billing info), the `element_mode` in `$form_state` should be separated by the form parents. 

For example, commerce_shipping module is installed, and there are two form elements in the same checkout form page. Once a `edit_button` within shipping info (or payment info) is clicked, the same `element_mode` value in `$form_state` is set into _edit_ by `ajaxSubmit()`.  Therefore, `#element_mode` in shipping info and payment info are _edit_. It caused another form element in payment info doesn't contain `edit_button`. 

Perhaps, the element mode name should be with the form parents.

```
$form_state->get('element_mode-' . $id_prefix . '-edit_button')
```

2017-08-24 10:31 UTC, ymhuang0808 commented on modules/order/src/Element/ProfileSelect.php
> +    $form_state->set('element_mode', $triggering_element['#element_mode']);
As previous mention, the `element_mode` key in form state should be changed into:

```
    $parents = implode('-', $triggering_element['#parents']);
    $element_mode_name = 'element_mode-' . $parents;

    $form_state->set($element_mode_name, $triggering_element['#element_mode']);
```

2017-08-29 07:01 UTC, ymhuang0808 commented
Hi @bojanz I would like to enhance the PR, should I create a PR into 8.x-2.x or profile_reuse branch?

2017-08-29 13:56 UTC, mglaman commented
@ymhuang0808 hm, yeah that's the problem with Github. I'll wait to see what @bojanz says.

But to follow up: one of the main issues is that the element does not work if there are multiple elements on the same page. Correct?

2017-08-29 22:23 UTC, ymhuang0808 commented
@mglaman Yes. I'm tring to fix that.

2017-08-31 02:02 UTC, ymhuang0808 commented
@bojanz and @mglaman The enhancement for the PR is ready to review on https://github.com/fliegen/commerce/commit/57c11175d279fe55db9454b4274608195211aeb8. I think I should create a new PR into profile_reuse branch.

The commit has a few changes:

- Make the "Edit" button available in multiple form elements
- If the value of address field is changed, it will create a new customer profile entity
- Fix in edit mode, the address field is not changed with profile_selection
- Add functional JavaScript tests for multiple form element

2018-07-18 17:06 UTC, bojanz commented
This PR is outdated, the issue has many updated patches.

2018-07-18 17:06 UTC, closed without merging