Issue #2901442 by sumanthkumarc: It would be nice to have to have setOffer method on Promotion entity
drupalcommerce/commerce pull request #770
Opened 2017-08-11 07:30 UTC by sumanthkumarc

2017-08-11 13:20 UTC, mglaman requested changes

2017-08-11 13:20 UTC, mglaman commented on modules/promotion/src/Entity/Promotion.php
> +  public function setOffer($target_plugin_id, array $target_plugin_configuration) {
We should pass an Offer plugin, and then the method knows how to extract the plugin ID and configuration

2017-08-15 11:10 UTC, bojanz commented on modules/promotion/src/Entity/Promotion.php
> +  public function setOffer($target_plugin_id, array $target_plugin_configuration) {
Agreed.

2017-08-16 05:14 UTC, sumanthkumarc commented on modules/promotion/src/Entity/Promotion.php
> +  public function setOffer($target_plugin_id, array $target_plugin_configuration) {
Thanks for the suggestion.

```php
// Returns array with plugin id and target config value.
$offer_plugin_config_array =  $promotion->get('offer')->first()->getValue();

// Returns offer plugin object of type PromotionOfferBase. Can we get all info from this object???
$offer_plugin_object =  $promotion->getOffer();
```

@mglaman which one should be passed to setOffer method?? as per my knowledge, $offer_object can be enforced for typehint but not sure if we get all reqd. info. from this object. i'm talking about configuration like amount etc. getConfiguration() doesn't help here, gives different keys.

if we pass the $offer_plugin_config_array, i'm not sure how we can enforce if the reqd. values are present and if user knows to get this value from??

2017-08-16 12:31 UTC, mglaman approved these changes

2017-08-16 12:31 UTC, mglaman commented
@sumanthkumarc can we update the entity's Kernel test to document / test the method?

2017-08-18 22:20 UTC, bojanz commented on modules/promotion/src/Entity/PromotionInterface.php
> +   *    The offer plugin.
Wrong indent of the param description (3 spaces instead of 2)

2017-08-18 22:20 UTC, bojanz commented on modules/promotion/src/Entity/PromotionInterface.php
> +   * @param \Drupal\commerce_promotion\Plugin\Commerce\PromotionOffer\PromotionOfferInterface $offer_plugin
$offer_plugin should be just $offer, we don't suffix like that.

2017-08-18 22:20 UTC, bojanz commented
Tweaked the code style, added a test, committed in b7f1cea4ea22b7f3dfae9c16096c73d98342294e.

2017-08-18 22:20 UTC, closed without merging