Issue #2903490 stop order item percentage promotions from creating negative order totals
drupalcommerce/commerce pull request #776
Opened 2017-08-21 06:53 UTC by swickham78

2017-09-08 16:18 UTC, mglaman requested changes
I really think we need a test, first, which proves the error.

2017-09-08 16:18 UTC, mglaman commented on modules/promotion/src/Plugin/Commerce/PromotionOffer/OrderItemPercentageOff.php
> +        $item_adjustment_total += (float) $item_adjustment->getAmount()->getNumber();
Why not use the price objects `add` method here?

```
$adjustment_total = new Price('0', $order_item->getUnitPrice()->getCurrencyCode();
foreach ($order_item->getAdjustments() as $adjustment) {
  $adjustment_total = $adjustment_total->add($adjustment->getAmount());
}
```

2017-09-08 16:18 UTC, mglaman commented on modules/promotion/src/Plugin/Commerce/PromotionOffer/OrderItemPercentageOff.php
> +    if (!$adjustment_amount->isZero()) {
This won't fix the issue

```
  public function isZero() {
    return Calculator::compare($this->number, '0') == 0;
  }
```

2018-07-18 17:05 UTC, bojanz commented
Let's continue on the issue. The patch will need a rewrite for the updated promotions in 2.8

2018-07-18 17:05 UTC, closed without merging