Added a way to limit a discount code to an email address.
drupalcommerce/commerce pull request #779
Opened 2017-08-24 17:27 UTC by rynner

2017-09-05 17:49 UTC, bojanz commented
Thanks! You are missing a unit test (see the other Commerce conditions for examples).

2017-09-05 17:52 UTC, bojanz requested changes

2017-09-05 17:52 UTC, bojanz commented on modules/order/src/Plugin/Commerce/Condition/OrderEmailAddress.php
> +    $form['email'] = [
You are using email and mail, instead of choosing one. That doesn't make sense. Let's just use "mail"

2017-09-05 17:52 UTC, bojanz commented on modules/order/src/Plugin/Commerce/Condition/OrderEmailAddress.php
> +
Unneeded newline at the start of the method.

2017-09-05 17:52 UTC, bojanz commented on modules/order/src/Plugin/Commerce/Condition/OrderEmailAddress.php
> +    if ($this->configuration['mail'] == $order->getEmail()) {
For brevity you can just "return $this->configuration['mail'] == $order->getEmail()";

2017-09-05 18:08 UTC, rynner commented
The code changes were easy enough but I was looking around and couldn't find an example of another commerce condition test. Could you possibly point me to one?

Thanks!

2017-09-05 18:51 UTC, bojanz commented
Here's an example test: https://github.com/drupalcommerce/commerce/blob/8.x-2.x/modules/order/tests/src/Unit/Plugin/Commerce/Condition/OrderCurrencyTest.php

mglaman and I also agreed that the class should be named OrderEmail instead of OrderEmailAddress (same with the ID, order_email instead of order_email_address)

2017-09-06 14:01 UTC, rynner commented
Ok no problem. I'll get to that in a day or so.

2017-09-08 16:10 UTC, mglaman requested changes
Documenting requested changes.

Example test method:

```
  /**
   * ::covers evaluate.
   */
  public function testEmptyOrder() {
    $condition = new OrderCurrency([
      'currencies' => ['USD'],
    ], 'order_currency', ['entity_type' => 'commerce_order']);
    $order = $this->prophesize(OrderInterface::class);
    $order->getEntityTypeId()->willReturn('commerce_order');
    $order->getTotalPrice()->willReturn(NULL);
    $order = $order->reveal();
    $this->assertFalse($condition->evaluate($order));
  }
```

2017-09-08 16:10 UTC, mglaman commented on modules/order/src/Plugin/Commerce/Condition/OrderEmailAddress.php
> +class OrderEmailAddress extends ConditionBase {
s/OrderEmailAddress/OrderEmail

2017-09-08 16:10 UTC, mglaman commented on modules/order/src/Plugin/Commerce/Condition/OrderEmailAddress.php
> + *   id = "order_email_address",
s/order_email_address/order_email

2017-09-15 21:58 UTC, rynner commented
Sorry for the delay, I made those changes and added test. Please let me know what, if any, other changes you'd like.

Thanks!

2017-09-16 11:13 UTC, bojanz requested changes

2017-09-16 11:13 UTC, bojanz commented on modules/order/tests/src/Unit/Plugin/Commerce/Condition/OrderEmailTest.php
> + * @coversDefaultClass \Drupal\commerce_order\Plugin\Commerce\Condition\OrderCustomerRole
Wrong class specified.

2017-09-16 11:13 UTC, bojanz commented on modules/order/tests/src/Unit/Plugin/Commerce/Condition/OrderEmailTest.php
> + * @group commerce, orderemail
Wrong group specified. It's always "commerce"

2017-09-16 11:13 UTC, bojanz commented on modules/order/tests/src/Unit/Plugin/Commerce/Condition/OrderEmailTest.php
> +    $this->assertFalse($condition->evaluate($order));
This only tests a non-matching case, but doesn't test the matching case (when the order has the "test@test.com" email)

2017-09-16 11:14 UTC, bojanz commented
Thanks! We're nearly there. Left a few last nitpicks. We also need to add a schema entry in order/config/schema/commerce_order.schema.yml, look at the "commerce.commerce_condition.plugin.order_customer_role" inside for an example.

2017-09-19 13:59 UTC, rynner commented
Hey guys,

I'm not sure why the tests are failing. When I run them locally they pass. Any insight?

Thanks.

2017-09-19 14:06 UTC, mglaman approved these changes

2017-09-19 14:08 UTC, mglaman commented
```
    1) Drupal\Tests\commerce\Functional\UninstallTest::testUninstall
    Drupal\Core\Config\Schema\SchemaIncompleteException: Schema errors for
    core.entity_form_display.commerce_order_item.default.default with the
    following errors:
    core.entity_form_display.commerce_order_item.default.default:content.quantity.settings.placeholder
    missing schema,
    core.entity_form_display.commerce_order_item.default.default:content.quantity.settings.step
    missing schema,
    core.entity_form_display.commerce_order_item.default.default:content.unit_price.settings.require_confirmation
    missing schema
```

Looks like our default config has settings which are missing in schema defined by core? This is odd.

2017-09-20 09:22 UTC, bojanz commented
Fixed the schema and committed in 6f0b34495c8b5e173309e304a73cf984f895f65e, thanks!

2017-09-20 09:22 UTC, closed without merging